name: trex_37
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astropy=3.2.3=py37h516909a_0
  - atomicwrites=1.3.0=py37_1
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.9.11=py37_0
  - cloudpickle=1.2.2=py_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.0=py37h7b6447c_0
  - dask-core=2.6.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.0=py37_1
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py37_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=243
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.15.1=py37_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py37he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - matplotlib=3.1.1=py37h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=7.2.0=py37_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1c=h516909a_0
  - packaging=19.2=py_0
  - pandas=0.25.2=py37he6710b0_0
  - parso=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.0=py37_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.3=py37h516909a_0
  - ptyprocess=0.6.0=py37_0
  - py=1.8.0=py37_0
  - py-opencv=3.4.2=py37hb342d67_1
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pytest=5.0.1=py37_0
  - pytest-arraydiff=0.3=py_0
  - pytest-astropy=0.6.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.4.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.1=py_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37h7b6447c_0
  - pyyaml=3.13=py37h14c3975_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.14.2=py37hf484d3e_1
  - scipy=1.1.0=py37h7c811a0_2
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.28.1=py37h28b3542_0
  - traitlets=4.3.3=py37_0
  - wcwidth=0.1.7=py37_0
  - wheel=0.33.6=py37_0
  - xarray=0.11.0=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - astrobase==0.4.0
    - astroquery==0.3.10.dev0
    - batman-package==2.4.6
    - cdips==0.0.0
    - corner==2.0.1
    - chardet==3.0.4
    - corner==2.0.1
    - dask==1.1.1
    - emcee==3.0rc2
    - idna==2.8
    - jplephem==2.9
    - parse==1.9.0
    - pillow==5.4.0
    - psycopg2==2.7.6.1
    - pyeebls==0.1.6
    - requests==2.21.0
    - scikit-learn==0.20.2
    - seaborn==0.9.0
    - tessmaps==0.1.0
    - urllib3==1.24.1
prefix: /home/lbouma/miniconda3/envs/trex_37

